import { CAST } from './scenario.js'
import type { SimEvent } from './recorders.js'
import type { DaySnapshot } from './run.js'

const GLYPH: Record<SimEvent['kind'], string> = {
  charge: '£',
  webhook: '•',
  email: '✉',
  status: '⇄',
  error: '!',
}

export function renderHtml(data: { snapshots: DaySnapshot[]; events: SimEvent[] }): string {
  const { snapshots, events } = data
  const rows = CAST.map((character) => renderRow(character, snapshots, events)).join('\n')

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Trove billing — simulation</title>
<style>${CSS}</style>
</head>
<body>
<header>
  <h1>Trove billing — ${snapshots.length} days simulated</h1>
  <p class="sub">Generated by <code>npm run simulate</code>. Reads only the subscription store, the
  charges handed to the processor, and the emails sent — nothing about how you built it.</p>
  <p class="legend">
    <span class="chip neutral">£ charge submitted</span>
    <span class="chip good">• payment received</span>
    <span class="chip bad">• declined</span>
    <span class="chip neutral">✉ email</span>
    <span class="chip bad">! error</span>
    <span class="chip band-active">active</span>
    <span class="chip band-past_due">past due</span>
    <span class="chip band-cancelled">cancelled</span>
  </p>
</header>

<section class="scroller">
  <table class="timeline">
    <thead>
      <tr>
        <th class="who">Subscription</th>
        ${snapshots.map((s) => `<th class="day"><span>${s.date.slice(8)}</span></th>`).join('')}
      </tr>
    </thead>
    <tbody>
${rows}
    </tbody>
  </table>
</section>

<section>
  <h2>What happened</h2>
  ${events.length === 0 ? '<p class="empty">Nothing at all. No charges, no emails, no status changes.</p>' : renderLog(events)}
</section>
</body>
</html>
`
}

function renderRow(
  character: (typeof CAST)[number],
  snapshots: DaySnapshot[],
  events: SimEvent[],
): string {
  const id = character.subscription.id
  const cells = snapshots
    .map((snapshot) => {
      const status = snapshot.statuses[id] ?? 'gone'
      const onThisDay = events.filter((e) => e.day === snapshot.day && e.subjectId === id)
      const marks = onThisDay
        .map(
          (e) =>
            `<i class="mark ${e.tone}" title="${escapeHtml(`${e.label} — ${e.detail}`)}">${GLYPH[e.kind]}</i>`,
        )
        .join('')
      return `<td class="band-${status}">${marks}</td>`
    })
    .join('')

  const plan = `${character.subscription.planId} ${character.subscription.period}`
  return `      <tr>
        <th class="who">
          <span class="name">${escapeHtml(character.customer.email.split('@')[0] ?? id)}</span>
          <span class="meta">${escapeHtml(plan)} · renews ${character.subscription.renewsAt.toISOString().slice(0, 10)}</span>
          <span class="note">${escapeHtml(character.note)}</span>
        </th>
${cells}
      </tr>`
}

function renderLog(events: SimEvent[]): string {
  const rows = events
    .map(
      (e) => `<tr class="${e.tone}">
      <td class="num">${e.day}</td>
      <td class="nowrap">${e.date}</td>
      <td class="nowrap">${escapeHtml(e.subjectId ?? '—')}</td>
      <td><span class="glyph ${e.tone}">${GLYPH[e.kind]}</span> ${escapeHtml(e.label)}</td>
      <td class="detail">${escapeHtml(e.detail)}</td>
    </tr>`,
    )
    .join('\n')

  return `<table class="log">
    <thead><tr><th>Day</th><th>Date</th><th>Subscription</th><th>Event</th><th>Detail</th></tr></thead>
    <tbody>${rows}</tbody>
  </table>`
}

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}

const CSS = `
:root {
  --bg: #fbfbfa; --fg: #23211d; --muted: #6f6a61; --line: #e3e0d8; --card: #ffffff;
  --good: #2f7a4d; --good-bg: #dcefe1; --bad: #b03a2b; --bad-bg: #f6ddd8;
  --neutral: #4a5f7a; --neutral-bg: #dde5ee;
  --active: #e7f2e9; --past_due: #fbeedd; --cancelled: #eceae5; --gone: #eceae5;
}
@media (prefers-color-scheme: dark) {
  :root {
    --bg: #171614; --fg: #e9e6df; --muted: #9a948a; --line: #322f2a; --card: #1e1d1a;
    --good: #7fc79a; --good-bg: #1f3529; --bad: #e08a79; --bad-bg: #3a221d;
    --neutral: #9db6d4; --neutral-bg: #1f2a37;
    --active: #1d2a22; --past_due: #33281a; --cancelled: #26241f; --gone: #26241f;
  }
}
* { box-sizing: border-box; }
body {
  margin: 0; padding: 2rem 1.5rem 4rem; background: var(--bg); color: var(--fg);
  font: 15px/1.5 ui-sans-serif, -apple-system, "Segoe UI", system-ui, sans-serif;
}
h1 { font-size: 1.35rem; margin: 0 0 .35rem; font-weight: 600; }
h2 { font-size: 1.05rem; margin: 2.5rem 0 .75rem; font-weight: 600; }
.sub { color: var(--muted); margin: 0 0 1rem; max-width: 62ch; font-size: .9rem; }
code { font-family: ui-monospace, SFMono-Regular, Menlo, monospace; font-size: .85em; }
.legend { display: flex; flex-wrap: wrap; gap: .4rem; margin: 0 0 1.5rem; }
.chip {
  font-size: .75rem; padding: .18rem .5rem; border-radius: 999px;
  border: 1px solid var(--line); color: var(--muted);
}
.chip.good { background: var(--good-bg); color: var(--good); border-color: transparent; }
.chip.bad { background: var(--bad-bg); color: var(--bad); border-color: transparent; }
.chip.neutral { background: var(--neutral-bg); color: var(--neutral); border-color: transparent; }
.chip.band-active { background: var(--active); }
.chip.band-past_due { background: var(--past_due); }
.chip.band-cancelled { background: var(--cancelled); }
.scroller { overflow-x: auto; border: 1px solid var(--line); border-radius: 10px; background: var(--card); }
table { border-collapse: collapse; width: 100%; }
.timeline th.day {
  font-weight: 500; font-size: .7rem; color: var(--muted); padding: .5rem .1rem;
  border-bottom: 1px solid var(--line); min-width: 26px;
}
.timeline th.who {
  text-align: left; padding: .6rem .9rem; border-bottom: 1px solid var(--line);
  border-right: 1px solid var(--line); position: sticky; left: 0; background: var(--card);
  min-width: 230px; font-weight: 500; vertical-align: top;
}
.timeline tbody th.who { border-top: 1px solid var(--line); }
.who .name { display: block; font-weight: 600; }
.who .meta { display: block; font-size: .75rem; color: var(--muted); }
.who .note { display: block; font-size: .75rem; color: var(--muted); font-style: italic; margin-top: .2rem; }
.timeline td {
  border-top: 1px solid var(--line); border-right: 1px solid var(--line);
  text-align: center; vertical-align: middle; height: 62px; padding: 0;
}
.band-active { background: var(--active); }
.band-past_due { background: var(--past_due); }
.band-cancelled, .band-gone { background: var(--cancelled); }
.mark {
  display: block; font-style: normal; font-size: .8rem; line-height: 1.25; cursor: help;
}
.mark.good { color: var(--good); }
.mark.bad { color: var(--bad); }
.mark.neutral { color: var(--neutral); }
.empty { color: var(--muted); font-style: italic; }
.log { font-size: .85rem; border: 1px solid var(--line); border-radius: 10px; background: var(--card); overflow: hidden; }
.log th {
  text-align: left; font-weight: 500; font-size: .75rem; color: var(--muted);
  padding: .5rem .75rem; border-bottom: 1px solid var(--line);
}
.log td { padding: .4rem .75rem; border-top: 1px solid var(--line); vertical-align: top; }
.log .num { text-align: right; color: var(--muted); }
.log .nowrap { white-space: nowrap; color: var(--muted); }
.log .detail { color: var(--muted); }
.glyph { display: inline-block; width: 1.1em; }
.glyph.good { color: var(--good); }
.glyph.bad { color: var(--bad); }
.glyph.neutral { color: var(--neutral); }
`
